apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: todo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: todo
      labels:
        k8s-app: todo
    spec:
      containers:
        - name: todo
          image: vduny.azurecr.io/todoserver
      restartPolicy: Always
